Add SBOM to Release NuGet package
Azure/azure-functions-durable-extension pull request #2097
Opened 2022-02-25 17:55 UTC by bachuv

This PR adds the SBOM manifest to the release NuGet package. It adds a `dotnet publish` step and moves the manifest generator step to come before the `dotnet pack` step. It also adds a .nuspec file that specifies the additional files that need to get added to the NuGet package during `dotnet pack`.

### Pull request checklist

* [x] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation PR is ready to merge and referenced in `pending_docs.md`
* [x] My changes **should not** be added to the release notes for the next release
    * [ ] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests)
* [x] My changes **do not** require any extra work to be leveraged by OutOfProc SDKs
    * [ ] Otherwise: That work is being tracked here: #issue_or_pr_in_each_sdk
* [x] My changes **do not** change the version of the WebJobs.Extensions.DurableTask package
    * [ ] Otherwise: major or minor version updates are reflected in `/src/Worker.Extensions.DurableTask/AssemblyInfo.cs`

2022-02-25 18:53 UTC, eliaslopezgt requested changes
LGTM just a change suggested by Adrian Diglio.

2022-02-25 18:53 UTC, eliaslopezgt commented on src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.nuspec
> +    <file src="..\..\_manifest\**" target="content/manifest"/>
Consider a more descriptive folder name e.g.
```suggestion
    <file src="..\..\_manifest\**" target="content/SBOM"/>
```

2022-02-25 23:02 UTC, davidmrdavid approved these changes
LGTM if it looks good to @eliaslopezgt

2022-02-28 18:03 UTC, eliaslopezgt approved these changes

2022-02-28 20:20 UTC, merged