[For private package] Add Entity Telemetry in exchange of EventGridNotification logs
Azure/azure-functions-durable-extension pull request #2587
Opened 2023-09-15 18:53 UTC by davidmrdavid

For private package only. IcM is = 423004777

As per [this](https://github.com/Azure/azure-functions-durable-extension/pull/2390#issuecomment-1516808217) comment, the EventIds for some of our entity telemetry is not showing up in our telemetry yet.

This draft PR is a hack that swaps the ETW EventIds of EventGridNotifications for the Entity ETW events. That should suffice to let these critical logs surface to our Kusto server for investigation's sake.

2023-09-18 18:05 UTC, sebastianburckhardt requested changes
I would update the version counter, otherwise seems fine

2023-09-18 18:05 UTC, sebastianburckhardt commented on src/WebJobs.Extensions.DurableTask/EtwEventSource.cs
> -        [Event(210, Level = EventLevel.Informational, Version = 3)]
I would set version to 5 here since the previous version of event 233 was 4.

2023-09-18 18:05 UTC, sebastianburckhardt commented on src/WebJobs.Extensions.DurableTask/EtwEventSource.cs
> -        [Event(211, Level = EventLevel.Error, Version = 3)]
similarly, use version 5 since previous version of event 234 was 4

2026-01-09 20:15 UTC, torosent commented
Closing stale PR. Please reopen if still relevant.

2026-01-09 20:15 UTC, closed without merging