Override new "base" Terminate API
Azure/azure-functions-durable-extension pull request #2829
Opened 2024-05-23 00:09 UTC by davidmrdavid

Follow up to: https://github.com/Azure/azure-functions-durable-extension/pull/2802

The PR made the `FunctionsDurableTaskClient` override new missing overloads from `DurableTaskClient` which were causing issues as reported here: https://github.com/microsoft/durabletask-dotnet/issues/282#issuecomment-2114590648

Seems we missed the `TerminateInstanceAsync` API in the PR above, so this PR adds it.

### Issue describing the changes in this PR

resolves https://github.com/microsoft/durabletask-dotnet/issues/282#issuecomment-2114590648

### Pull request checklist

* [ ] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation PR is ready to merge and referenced in `pending_docs.md`
* [ ] My changes **should not** be added to the release notes for the next release
    * [ ] Otherwise: I've added my notes to `release_notes.md`
* [ ] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ ] I have added all required tests (Unit tests, E2E tests)
* [ ] My changes **do not** require any extra work to be leveraged by OutOfProc SDKs
    * [ ] Otherwise: That work is being tracked here: #issue_or_pr_in_each_sdk
* [ ] My changes **do not** change the version of the WebJobs.Extensions.DurableTask package
    * [ ] Otherwise: major or minor version updates are reflected in `/src/Worker.Extensions.DurableTask/AssemblyInfo.cs`
* [ ] My changes **do not** add EventIds to our EventSource logs
    * [ ] Otherwise: Ensure the EventIds are within the supported range in our existing Windows infrastructure. You may validate this with a deployed app's telemetry. You may also extend the range by completing a PR such as [this one](https://msazure.visualstudio.com/One/_git/AAPT-Antares-Websites/pullrequest/7463263?_a=files).
* [ ] My changes **should** be added to v3.x branch.
    * [ ] Otherwise: This change only applies to Durable Functions v2.x and **will not** be merged to branch v3.x.

2024-05-23 04:20 UTC, jviau requested changes

2024-05-23 04:20 UTC, jviau commented on src/Worker.Extensions.DurableTask/FunctionsDurableTaskClient.cs
> +        return this.inner.TerminateInstanceAsync(instanceId, output: output, cancellation);
We should be passing the options directly to the inner call:

```suggestion
        return this.inner.TerminateInstanceAsync(instanceId, options, cancellation);
```

2024-05-23 20:18 UTC, davidmrdavid commented on src/Worker.Extensions.DurableTask/AssemblyInfo.cs
> +[assembly: InternalsVisibleTo("Worker.Extensions.DurableTask.Tests, PublicKey=0024000004800000940000000602000000240000525341310004000001000100cd1dabd5a893b40e75dc901fe7293db4a3caf9cd4d3e3ed6178d49cd4
So that internal classes can be tested in the tests project. This is a standard pattern, and we use it for the DF WebJobs Extension tests afaik.

2024-05-23 20:18 UTC, davidmrdavid commented on src/Worker.Extensions.DurableTask/HTTP/HttpMethodConverter.cs
> +        return new HttpMethod(readerString);
There was a small warning that `reader.GetString()` might return `null`. So I added this to make sure the method was well typed.

2024-05-24 16:17 UTC, jviau approved these changes

2024-05-28 17:20 UTC, merged